# Generated by Django 2.2.1 on 2019-05-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doghouse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pets',
            old_name='pet',
            new_name='pet_id',
        ),
    ]
