# Generated by Django 2.2.1 on 2019-05-13 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doghouse', '0002_auto_20190513_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pets',
            name='especie',
            field=models.CharField(choices=[('C', 'Cachorro'), ('G', 'Gato')], default='C', max_length=1),
        ),
    ]
