# Generated by Django 2.2.1 on 2019-05-13 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doghouse', '0003_auto_20190513_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pets',
            name='pet_id',
        ),
    ]
